"""Order the records list from indexes

Revision ID: 9555c7d5210e
Revises: 705a5ce77b66
Create Date: 2026-09-25 18:46:06.488960
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9555c7d5210e"
down_revision: str | Sequence[str] | None = "705a5ce77b66"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_records_project_id_title",
        "records",
        ["project_id", "title_norm", sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_index(
        "ix_records_project_id_year",
        "records",
        ["project_id", sa.literal_column("year DESC NULLS LAST"), sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_index(
        "ix_records_project_id_year_asc",
        "records",
        ["project_id", "year", sa.literal_column("id DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_records_project_id_year_asc", table_name="records")
    op.drop_index("ix_records_project_id_year", table_name="records")
    op.drop_index("ix_records_project_id_title", table_name="records")
    # ### end Alembic commands ###
