"""In-app notifications (guide 8.17)

Revision ID: 94e888a19128
Revises: a4b63e6c393d
Create Date: 2026-09-25 08:17:17.746622
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "94e888a19128"
down_revision: str | Sequence[str] | None = "a4b63e6c393d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_notifications_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_user_id_updated_at",
        "notifications",
        ["user_id", "updated_at"],
        unique=False,
    )
    op.create_index(
        "uq_notifications_unread_conflicts",
        "notifications",
        ["user_id", "project_id"],
        unique=True,
        postgresql_where="kind = 'conflicts' AND read_at IS NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_notifications_unread_conflicts",
        table_name="notifications",
        postgresql_where="kind = 'conflicts' AND read_at IS NULL",
    )
    op.drop_index("ix_notifications_user_id_updated_at", table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
