"""Extraction forms, entries and consensus (guide 8.12), with row-level security on what
people extracted, as on their decisions.

Revision ID: a4b63e6c393d
Revises: e2bea7d974ea
Create Date: 2026-09-25 06:40:37.128017
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a4b63e6c393d"
down_revision: str | Sequence[str] | None = "e2bea7d974ea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

APP_ROLE = "winnow_app"
# What people extracted is blinded like their decisions, and guarded the same way.
GUARDED = ("extraction_entries", "extraction_consensus")
MEMBER_OF = (
    "project_id IN (SELECT m.project_id FROM project_members m "
    "WHERE m.user_id = nullif(current_setting('app.user_id', true), '')::uuid)"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "extraction_forms",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dual", sa.Boolean(), nullable=False),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_extraction_forms_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_extraction_forms_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extraction_forms")),
        sa.UniqueConstraint(
            "family_id", "version", name=op.f("uq_extraction_forms_family_id_version")
        ),
    )
    op.create_index(
        "ix_extraction_forms_project_id", "extraction_forms", ["project_id"], unique=False
    )
    op.create_table(
        "extraction_consensus",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("form_id", sa.UUID(), nullable=False),
        sa.Column("record_id", sa.UUID(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("resolved_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["form_id"],
            ["extraction_forms.id"],
            name=op.f("fk_extraction_consensus_form_id_extraction_forms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_extraction_consensus_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["records.id"],
            name=op.f("fk_extraction_consensus_record_id_records"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["users.id"],
            name=op.f("fk_extraction_consensus_resolved_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extraction_consensus")),
        sa.UniqueConstraint(
            "form_id", "record_id", name=op.f("uq_extraction_consensus_form_id_record_id")
        ),
    )
    op.create_index(
        "ix_extraction_consensus_project_id", "extraction_consensus", ["project_id"], unique=False
    )
    op.create_table(
        "extraction_entries",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("form_id", sa.UUID(), nullable=False),
        sa.Column("record_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "submitted", "verified", name="extraction_entry_status"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["form_id"],
            ["extraction_forms.id"],
            name=op.f("fk_extraction_entries_form_id_extraction_forms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_extraction_entries_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["records.id"],
            name=op.f("fk_extraction_entries_record_id_records"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_extraction_entries_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extraction_entries")),
        sa.UniqueConstraint(
            "form_id",
            "record_id",
            "user_id",
            name=op.f("uq_extraction_entries_form_id_record_id_user_id"),
        ),
    )
    op.create_index(
        "ix_extraction_entries_project_id", "extraction_entries", ["project_id"], unique=False
    )
    # ### end Alembic commands ###
    # Extracted data is exported like records. (PostgreSQL cannot drop an enum value; the
    # downgrade leaves it, unused.)
    op.execute("ALTER TYPE export_kind ADD VALUE IF NOT EXISTS 'extraction'")
    for table in GUARDED:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {table}_members_only ON {table} TO {APP_ROLE} "
            f"USING ({MEMBER_OF}) WITH CHECK ({MEMBER_OF})"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_extraction_entries_project_id", table_name="extraction_entries")
    op.drop_table("extraction_entries")
    op.drop_index("ix_extraction_consensus_project_id", table_name="extraction_consensus")
    op.drop_table("extraction_consensus")
    op.drop_index("ix_extraction_forms_project_id", table_name="extraction_forms")
    op.drop_table("extraction_forms")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS extraction_entry_status")
