/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppNewRouteImport } from './routes/_app/new'
import { Route as AppRestoreRouteImport } from './routes/_app/restore'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ResetTokenRouteImport } from './routes/reset.$token'
import { Route as VerifyTokenRouteImport } from './routes/verify.$token'
import { Route as AppPPidRouteImport } from './routes/_app/p/$pid'
import { Route as AppPPidIndexRouteImport } from './routes/_app/p/$pid/index'
import { Route as AppPPidConflictsRouteImport } from './routes/_app/p/$pid/conflicts'
import { Route as AppPPidDuplicatesRouteImport } from './routes/_app/p/$pid/duplicates'
import { Route as AppPPidImportRouteImport } from './routes/_app/p/$pid/import'
import { Route as AppPPidRecordsRouteImport } from './routes/_app/p/$pid/records'
import { Route as AppPPidReportRouteImport } from './routes/_app/p/$pid/report'
import { Route as AppPPidRobRouteImport } from './routes/_app/p/$pid/rob'
import { Route as AppPPidSettingsRouteImport } from './routes/_app/p/$pid/settings'
import { Route as AppPPidReportIndexRouteImport } from './routes/_app/p/$pid/report/index'
import { Route as AppPPidReportAuditRouteImport } from './routes/_app/p/$pid/report/audit'
import { Route as AppPPidReportExportsRouteImport } from './routes/_app/p/$pid/report/exports'
import { Route as AppPPidReportStatsRouteImport } from './routes/_app/p/$pid/report/stats'
import { Route as AppPPidScreenFtRouteImport } from './routes/_app/p/$pid/screen/ft'
import { Route as AppPPidScreenTaRouteImport } from './routes/_app/p/$pid/screen/ta'
import { Route as AppPPidSettingsIndexRouteImport } from './routes/_app/p/$pid/settings/index'
import { Route as AppPPidSettingsCriteriaRouteImport } from './routes/_app/p/$pid/settings/criteria'
import { Route as AppPPidSettingsKeywordsRouteImport } from './routes/_app/p/$pid/settings/keywords'
import { Route as AppPPidSettingsLabelsRouteImport } from './routes/_app/p/$pid/settings/labels'
import { Route as AppPPidSettingsReasonsRouteImport } from './routes/_app/p/$pid/settings/reasons'
import { Route as AppPPidSettingsScreeningRouteImport } from './routes/_app/p/$pid/settings/screening'
import { Route as AppPPidSettingsTeamRouteImport } from './routes/_app/p/$pid/settings/team'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppRestoreRoute = AppRestoreRouteImport.update({
  id: '/restore',
  path: '/restore',
  getParentRoute: () => AppRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetTokenRoute = ResetTokenRouteImport.update({
  id: '/reset/$token',
  path: '/reset/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTokenRoute = VerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPPidRoute = AppPPidRouteImport.update({
  id: '/p/$pid',
  path: '/p/$pid',
  getParentRoute: () => AppRoute,
} as any)
const AppPPidIndexRoute = AppPPidIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPPidRoute,
} as any)
const AppPPidConflictsRoute = AppPPidConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => AppPPidRoute,
} as any)
const AppPPidDuplicatesRoute = AppPPidDuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => AppPPidRoute,
} as any)
const AppPPidImportRoute = AppPPidImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppPPidRoute,
} as any)
const AppPPidRecordsRoute = AppPPidRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AppPPidRoute,
} as any)
const AppPPidReportRoute = AppPPidReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppPPidRoute,
} as any)
const AppPPidRobRoute = AppPPidRobRouteImport.update({
  id: '/rob',
  path: '/rob',
  getParentRoute: () => AppPPidRoute,
} as any)
const AppPPidSettingsRoute = AppPPidSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppPPidRoute,
} as any)
const AppPPidReportIndexRoute = AppPPidReportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPPidReportRoute,
} as any)
const AppPPidReportAuditRoute = AppPPidReportAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppPPidReportRoute,
} as any)
const AppPPidReportExportsRoute = AppPPidReportExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AppPPidReportRoute,
} as any)
const AppPPidReportStatsRoute = AppPPidReportStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppPPidReportRoute,
} as any)
const AppPPidScreenFtRoute = AppPPidScreenFtRouteImport.update({
  id: '/screen/ft',
  path: '/screen/ft',
  getParentRoute: () => AppPPidRoute,
} as any)
const AppPPidScreenTaRoute = AppPPidScreenTaRouteImport.update({
  id: '/screen/ta',
  path: '/screen/ta',
  getParentRoute: () => AppPPidRoute,
} as any)
const AppPPidSettingsIndexRoute = AppPPidSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPPidSettingsRoute,
} as any)
const AppPPidSettingsCriteriaRoute = AppPPidSettingsCriteriaRouteImport.update({
  id: '/criteria',
  path: '/criteria',
  getParentRoute: () => AppPPidSettingsRoute,
} as any)
const AppPPidSettingsKeywordsRoute = AppPPidSettingsKeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => AppPPidSettingsRoute,
} as any)
const AppPPidSettingsLabelsRoute = AppPPidSettingsLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AppPPidSettingsRoute,
} as any)
const AppPPidSettingsReasonsRoute = AppPPidSettingsReasonsRouteImport.update({
  id: '/reasons',
  path: '/reasons',
  getParentRoute: () => AppPPidSettingsRoute,
} as any)
const AppPPidSettingsScreeningRoute =
  AppPPidSettingsScreeningRouteImport.update({
    id: '/screening',
    path: '/screening',
    getParentRoute: () => AppPPidSettingsRoute,
  } as any)
const AppPPidSettingsTeamRoute = AppPPidSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppPPidSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/account': typeof AppAccountRoute
  '/new': typeof AppNewRoute
  '/restore': typeof AppRestoreRoute
  '/invite/$token': typeof InviteTokenRoute
  '/reset/$token': typeof ResetTokenRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/p/$pid': typeof AppPPidRouteWithChildren
  '/p/$pid/conflicts': typeof AppPPidConflictsRoute
  '/p/$pid/duplicates': typeof AppPPidDuplicatesRoute
  '/p/$pid/import': typeof AppPPidImportRoute
  '/p/$pid/records': typeof AppPPidRecordsRoute
  '/p/$pid/report': typeof AppPPidReportRouteWithChildren
  '/p/$pid/rob': typeof AppPPidRobRoute
  '/p/$pid/settings': typeof AppPPidSettingsRouteWithChildren
  '/p/$pid/': typeof AppPPidIndexRoute
  '/p/$pid/report/audit': typeof AppPPidReportAuditRoute
  '/p/$pid/report/exports': typeof AppPPidReportExportsRoute
  '/p/$pid/report/stats': typeof AppPPidReportStatsRoute
  '/p/$pid/screen/ft': typeof AppPPidScreenFtRoute
  '/p/$pid/screen/ta': typeof AppPPidScreenTaRoute
  '/p/$pid/settings/criteria': typeof AppPPidSettingsCriteriaRoute
  '/p/$pid/settings/keywords': typeof AppPPidSettingsKeywordsRoute
  '/p/$pid/settings/labels': typeof AppPPidSettingsLabelsRoute
  '/p/$pid/settings/reasons': typeof AppPPidSettingsReasonsRoute
  '/p/$pid/settings/screening': typeof AppPPidSettingsScreeningRoute
  '/p/$pid/settings/team': typeof AppPPidSettingsTeamRoute
  '/p/$pid/report/': typeof AppPPidReportIndexRoute
  '/p/$pid/settings/': typeof AppPPidSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/account': typeof AppAccountRoute
  '/new': typeof AppNewRoute
  '/restore': typeof AppRestoreRoute
  '/invite/$token': typeof InviteTokenRoute
  '/reset/$token': typeof ResetTokenRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/': typeof AppIndexRoute
  '/p/$pid/conflicts': typeof AppPPidConflictsRoute
  '/p/$pid/duplicates': typeof AppPPidDuplicatesRoute
  '/p/$pid/import': typeof AppPPidImportRoute
  '/p/$pid/records': typeof AppPPidRecordsRoute
  '/p/$pid/rob': typeof AppPPidRobRoute
  '/p/$pid': typeof AppPPidIndexRoute
  '/p/$pid/report/audit': typeof AppPPidReportAuditRoute
  '/p/$pid/report/exports': typeof AppPPidReportExportsRoute
  '/p/$pid/report/stats': typeof AppPPidReportStatsRoute
  '/p/$pid/screen/ft': typeof AppPPidScreenFtRoute
  '/p/$pid/screen/ta': typeof AppPPidScreenTaRoute
  '/p/$pid/settings/criteria': typeof AppPPidSettingsCriteriaRoute
  '/p/$pid/settings/keywords': typeof AppPPidSettingsKeywordsRoute
  '/p/$pid/settings/labels': typeof AppPPidSettingsLabelsRoute
  '/p/$pid/settings/reasons': typeof AppPPidSettingsReasonsRoute
  '/p/$pid/settings/screening': typeof AppPPidSettingsScreeningRoute
  '/p/$pid/settings/team': typeof AppPPidSettingsTeamRoute
  '/p/$pid/report': typeof AppPPidReportIndexRoute
  '/p/$pid/settings': typeof AppPPidSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/new': typeof AppNewRoute
  '/_app/restore': typeof AppRestoreRoute
  '/invite/$token': typeof InviteTokenRoute
  '/reset/$token': typeof ResetTokenRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/p/$pid': typeof AppPPidRouteWithChildren
  '/_app/p/$pid/conflicts': typeof AppPPidConflictsRoute
  '/_app/p/$pid/duplicates': typeof AppPPidDuplicatesRoute
  '/_app/p/$pid/import': typeof AppPPidImportRoute
  '/_app/p/$pid/records': typeof AppPPidRecordsRoute
  '/_app/p/$pid/report': typeof AppPPidReportRouteWithChildren
  '/_app/p/$pid/rob': typeof AppPPidRobRoute
  '/_app/p/$pid/settings': typeof AppPPidSettingsRouteWithChildren
  '/_app/p/$pid/': typeof AppPPidIndexRoute
  '/_app/p/$pid/report/audit': typeof AppPPidReportAuditRoute
  '/_app/p/$pid/report/exports': typeof AppPPidReportExportsRoute
  '/_app/p/$pid/report/stats': typeof AppPPidReportStatsRoute
  '/_app/p/$pid/screen/ft': typeof AppPPidScreenFtRoute
  '/_app/p/$pid/screen/ta': typeof AppPPidScreenTaRoute
  '/_app/p/$pid/settings/criteria': typeof AppPPidSettingsCriteriaRoute
  '/_app/p/$pid/settings/keywords': typeof AppPPidSettingsKeywordsRoute
  '/_app/p/$pid/settings/labels': typeof AppPPidSettingsLabelsRoute
  '/_app/p/$pid/settings/reasons': typeof AppPPidSettingsReasonsRoute
  '/_app/p/$pid/settings/screening': typeof AppPPidSettingsScreeningRoute
  '/_app/p/$pid/settings/team': typeof AppPPidSettingsTeamRoute
  '/_app/p/$pid/report/': typeof AppPPidReportIndexRoute
  '/_app/p/$pid/settings/': typeof AppPPidSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot'
    | '/login'
    | '/register'
    | '/setup'
    | '/account'
    | '/new'
    | '/restore'
    | '/invite/$token'
    | '/reset/$token'
    | '/verify/$token'
    | '/p/$pid'
    | '/p/$pid/conflicts'
    | '/p/$pid/duplicates'
    | '/p/$pid/import'
    | '/p/$pid/records'
    | '/p/$pid/report'
    | '/p/$pid/rob'
    | '/p/$pid/settings'
    | '/p/$pid/'
    | '/p/$pid/report/audit'
    | '/p/$pid/report/exports'
    | '/p/$pid/report/stats'
    | '/p/$pid/screen/ft'
    | '/p/$pid/screen/ta'
    | '/p/$pid/settings/criteria'
    | '/p/$pid/settings/keywords'
    | '/p/$pid/settings/labels'
    | '/p/$pid/settings/reasons'
    | '/p/$pid/settings/screening'
    | '/p/$pid/settings/team'
    | '/p/$pid/report/'
    | '/p/$pid/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot'
    | '/login'
    | '/register'
    | '/setup'
    | '/account'
    | '/new'
    | '/restore'
    | '/invite/$token'
    | '/reset/$token'
    | '/verify/$token'
    | '/'
    | '/p/$pid/conflicts'
    | '/p/$pid/duplicates'
    | '/p/$pid/import'
    | '/p/$pid/records'
    | '/p/$pid/rob'
    | '/p/$pid'
    | '/p/$pid/report/audit'
    | '/p/$pid/report/exports'
    | '/p/$pid/report/stats'
    | '/p/$pid/screen/ft'
    | '/p/$pid/screen/ta'
    | '/p/$pid/settings/criteria'
    | '/p/$pid/settings/keywords'
    | '/p/$pid/settings/labels'
    | '/p/$pid/settings/reasons'
    | '/p/$pid/settings/screening'
    | '/p/$pid/settings/team'
    | '/p/$pid/report'
    | '/p/$pid/settings'
  id:
    | '__root__'
    | '/_app'
    | '/forgot'
    | '/login'
    | '/register'
    | '/setup'
    | '/_app/account'
    | '/_app/new'
    | '/_app/restore'
    | '/invite/$token'
    | '/reset/$token'
    | '/verify/$token'
    | '/_app/'
    | '/_app/p/$pid'
    | '/_app/p/$pid/conflicts'
    | '/_app/p/$pid/duplicates'
    | '/_app/p/$pid/import'
    | '/_app/p/$pid/records'
    | '/_app/p/$pid/report'
    | '/_app/p/$pid/rob'
    | '/_app/p/$pid/settings'
    | '/_app/p/$pid/'
    | '/_app/p/$pid/report/audit'
    | '/_app/p/$pid/report/exports'
    | '/_app/p/$pid/report/stats'
    | '/_app/p/$pid/screen/ft'
    | '/_app/p/$pid/screen/ta'
    | '/_app/p/$pid/settings/criteria'
    | '/_app/p/$pid/settings/keywords'
    | '/_app/p/$pid/settings/labels'
    | '/_app/p/$pid/settings/reasons'
    | '/_app/p/$pid/settings/screening'
    | '/_app/p/$pid/settings/team'
    | '/_app/p/$pid/report/'
    | '/_app/p/$pid/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SetupRoute: typeof SetupRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ResetTokenRoute: typeof ResetTokenRoute
  VerifyTokenRoute: typeof VerifyTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new': {
      id: '/_app/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restore': {
      id: '/_app/restore'
      path: '/restore'
      fullPath: '/restore'
      preLoaderRoute: typeof AppRestoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset/$token': {
      id: '/reset/$token'
      path: '/reset/$token'
      fullPath: '/reset/$token'
      preLoaderRoute: typeof ResetTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$token': {
      id: '/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/p/$pid': {
      id: '/_app/p/$pid'
      path: '/p/$pid'
      fullPath: '/p/$pid'
      preLoaderRoute: typeof AppPPidRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/p/$pid/': {
      id: '/_app/p/$pid/'
      path: '/'
      fullPath: '/p/$pid/'
      preLoaderRoute: typeof AppPPidIndexRouteImport
      parentRoute: typeof AppPPidRoute
    }
    '/_app/p/$pid/conflicts': {
      id: '/_app/p/$pid/conflicts'
      path: '/conflicts'
      fullPath: '/p/$pid/conflicts'
      preLoaderRoute: typeof AppPPidConflictsRouteImport
      parentRoute: typeof AppPPidRoute
    }
    '/_app/p/$pid/duplicates': {
      id: '/_app/p/$pid/duplicates'
      path: '/duplicates'
      fullPath: '/p/$pid/duplicates'
      preLoaderRoute: typeof AppPPidDuplicatesRouteImport
      parentRoute: typeof AppPPidRoute
    }
    '/_app/p/$pid/import': {
      id: '/_app/p/$pid/import'
      path: '/import'
      fullPath: '/p/$pid/import'
      preLoaderRoute: typeof AppPPidImportRouteImport
      parentRoute: typeof AppPPidRoute
    }
    '/_app/p/$pid/records': {
      id: '/_app/p/$pid/records'
      path: '/records'
      fullPath: '/p/$pid/records'
      preLoaderRoute: typeof AppPPidRecordsRouteImport
      parentRoute: typeof AppPPidRoute
    }
    '/_app/p/$pid/report': {
      id: '/_app/p/$pid/report'
      path: '/report'
      fullPath: '/p/$pid/report'
      preLoaderRoute: typeof AppPPidReportRouteImport
      parentRoute: typeof AppPPidRoute
    }
    '/_app/p/$pid/rob': {
      id: '/_app/p/$pid/rob'
      path: '/rob'
      fullPath: '/p/$pid/rob'
      preLoaderRoute: typeof AppPPidRobRouteImport
      parentRoute: typeof AppPPidRoute
    }
    '/_app/p/$pid/settings': {
      id: '/_app/p/$pid/settings'
      path: '/settings'
      fullPath: '/p/$pid/settings'
      preLoaderRoute: typeof AppPPidSettingsRouteImport
      parentRoute: typeof AppPPidRoute
    }
    '/_app/p/$pid/report/': {
      id: '/_app/p/$pid/report/'
      path: '/'
      fullPath: '/p/$pid/report/'
      preLoaderRoute: typeof AppPPidReportIndexRouteImport
      parentRoute: typeof AppPPidReportRoute
    }
    '/_app/p/$pid/report/audit': {
      id: '/_app/p/$pid/report/audit'
      path: '/audit'
      fullPath: '/p/$pid/report/audit'
      preLoaderRoute: typeof AppPPidReportAuditRouteImport
      parentRoute: typeof AppPPidReportRoute
    }
    '/_app/p/$pid/report/exports': {
      id: '/_app/p/$pid/report/exports'
      path: '/exports'
      fullPath: '/p/$pid/report/exports'
      preLoaderRoute: typeof AppPPidReportExportsRouteImport
      parentRoute: typeof AppPPidReportRoute
    }
    '/_app/p/$pid/report/stats': {
      id: '/_app/p/$pid/report/stats'
      path: '/stats'
      fullPath: '/p/$pid/report/stats'
      preLoaderRoute: typeof AppPPidReportStatsRouteImport
      parentRoute: typeof AppPPidReportRoute
    }
    '/_app/p/$pid/screen/ft': {
      id: '/_app/p/$pid/screen/ft'
      path: '/screen/ft'
      fullPath: '/p/$pid/screen/ft'
      preLoaderRoute: typeof AppPPidScreenFtRouteImport
      parentRoute: typeof AppPPidRoute
    }
    '/_app/p/$pid/screen/ta': {
      id: '/_app/p/$pid/screen/ta'
      path: '/screen/ta'
      fullPath: '/p/$pid/screen/ta'
      preLoaderRoute: typeof AppPPidScreenTaRouteImport
      parentRoute: typeof AppPPidRoute
    }
    '/_app/p/$pid/settings/': {
      id: '/_app/p/$pid/settings/'
      path: '/'
      fullPath: '/p/$pid/settings/'
      preLoaderRoute: typeof AppPPidSettingsIndexRouteImport
      parentRoute: typeof AppPPidSettingsRoute
    }
    '/_app/p/$pid/settings/criteria': {
      id: '/_app/p/$pid/settings/criteria'
      path: '/criteria'
      fullPath: '/p/$pid/settings/criteria'
      preLoaderRoute: typeof AppPPidSettingsCriteriaRouteImport
      parentRoute: typeof AppPPidSettingsRoute
    }
    '/_app/p/$pid/settings/keywords': {
      id: '/_app/p/$pid/settings/keywords'
      path: '/keywords'
      fullPath: '/p/$pid/settings/keywords'
      preLoaderRoute: typeof AppPPidSettingsKeywordsRouteImport
      parentRoute: typeof AppPPidSettingsRoute
    }
    '/_app/p/$pid/settings/labels': {
      id: '/_app/p/$pid/settings/labels'
      path: '/labels'
      fullPath: '/p/$pid/settings/labels'
      preLoaderRoute: typeof AppPPidSettingsLabelsRouteImport
      parentRoute: typeof AppPPidSettingsRoute
    }
    '/_app/p/$pid/settings/reasons': {
      id: '/_app/p/$pid/settings/reasons'
      path: '/reasons'
      fullPath: '/p/$pid/settings/reasons'
      preLoaderRoute: typeof AppPPidSettingsReasonsRouteImport
      parentRoute: typeof AppPPidSettingsRoute
    }
    '/_app/p/$pid/settings/screening': {
      id: '/_app/p/$pid/settings/screening'
      path: '/screening'
      fullPath: '/p/$pid/settings/screening'
      preLoaderRoute: typeof AppPPidSettingsScreeningRouteImport
      parentRoute: typeof AppPPidSettingsRoute
    }
    '/_app/p/$pid/settings/team': {
      id: '/_app/p/$pid/settings/team'
      path: '/team'
      fullPath: '/p/$pid/settings/team'
      preLoaderRoute: typeof AppPPidSettingsTeamRouteImport
      parentRoute: typeof AppPPidSettingsRoute
    }
  }
}

interface AppPPidReportRouteChildren {
  AppPPidReportAuditRoute: typeof AppPPidReportAuditRoute
  AppPPidReportExportsRoute: typeof AppPPidReportExportsRoute
  AppPPidReportStatsRoute: typeof AppPPidReportStatsRoute
  AppPPidReportIndexRoute: typeof AppPPidReportIndexRoute
}

const AppPPidReportRouteChildren: AppPPidReportRouteChildren = {
  AppPPidReportAuditRoute: AppPPidReportAuditRoute,
  AppPPidReportExportsRoute: AppPPidReportExportsRoute,
  AppPPidReportStatsRoute: AppPPidReportStatsRoute,
  AppPPidReportIndexRoute: AppPPidReportIndexRoute,
}

const AppPPidReportRouteWithChildren = AppPPidReportRoute._addFileChildren(
  AppPPidReportRouteChildren,
)

interface AppPPidSettingsRouteChildren {
  AppPPidSettingsCriteriaRoute: typeof AppPPidSettingsCriteriaRoute
  AppPPidSettingsKeywordsRoute: typeof AppPPidSettingsKeywordsRoute
  AppPPidSettingsLabelsRoute: typeof AppPPidSettingsLabelsRoute
  AppPPidSettingsReasonsRoute: typeof AppPPidSettingsReasonsRoute
  AppPPidSettingsScreeningRoute: typeof AppPPidSettingsScreeningRoute
  AppPPidSettingsTeamRoute: typeof AppPPidSettingsTeamRoute
  AppPPidSettingsIndexRoute: typeof AppPPidSettingsIndexRoute
}

const AppPPidSettingsRouteChildren: AppPPidSettingsRouteChildren = {
  AppPPidSettingsCriteriaRoute: AppPPidSettingsCriteriaRoute,
  AppPPidSettingsKeywordsRoute: AppPPidSettingsKeywordsRoute,
  AppPPidSettingsLabelsRoute: AppPPidSettingsLabelsRoute,
  AppPPidSettingsReasonsRoute: AppPPidSettingsReasonsRoute,
  AppPPidSettingsScreeningRoute: AppPPidSettingsScreeningRoute,
  AppPPidSettingsTeamRoute: AppPPidSettingsTeamRoute,
  AppPPidSettingsIndexRoute: AppPPidSettingsIndexRoute,
}

const AppPPidSettingsRouteWithChildren = AppPPidSettingsRoute._addFileChildren(
  AppPPidSettingsRouteChildren,
)

interface AppPPidRouteChildren {
  AppPPidConflictsRoute: typeof AppPPidConflictsRoute
  AppPPidDuplicatesRoute: typeof AppPPidDuplicatesRoute
  AppPPidImportRoute: typeof AppPPidImportRoute
  AppPPidRecordsRoute: typeof AppPPidRecordsRoute
  AppPPidReportRoute: typeof AppPPidReportRouteWithChildren
  AppPPidRobRoute: typeof AppPPidRobRoute
  AppPPidSettingsRoute: typeof AppPPidSettingsRouteWithChildren
  AppPPidIndexRoute: typeof AppPPidIndexRoute
  AppPPidScreenFtRoute: typeof AppPPidScreenFtRoute
  AppPPidScreenTaRoute: typeof AppPPidScreenTaRoute
}

const AppPPidRouteChildren: AppPPidRouteChildren = {
  AppPPidConflictsRoute: AppPPidConflictsRoute,
  AppPPidDuplicatesRoute: AppPPidDuplicatesRoute,
  AppPPidImportRoute: AppPPidImportRoute,
  AppPPidRecordsRoute: AppPPidRecordsRoute,
  AppPPidReportRoute: AppPPidReportRouteWithChildren,
  AppPPidRobRoute: AppPPidRobRoute,
  AppPPidSettingsRoute: AppPPidSettingsRouteWithChildren,
  AppPPidIndexRoute: AppPPidIndexRoute,
  AppPPidScreenFtRoute: AppPPidScreenFtRoute,
  AppPPidScreenTaRoute: AppPPidScreenTaRoute,
}

const AppPPidRouteWithChildren =
  AppPPidRoute._addFileChildren(AppPPidRouteChildren)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppNewRoute: typeof AppNewRoute
  AppRestoreRoute: typeof AppRestoreRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPPidRoute: typeof AppPPidRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppNewRoute: AppNewRoute,
  AppRestoreRoute: AppRestoreRoute,
  AppIndexRoute: AppIndexRoute,
  AppPPidRoute: AppPPidRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SetupRoute: SetupRoute,
  InviteTokenRoute: InviteTokenRoute,
  ResetTokenRoute: ResetTokenRoute,
  VerifyTokenRoute: VerifyTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
